name: Deploy
on:
  workflow_run:
    workflows: ["Duplicated Test Workflow"]
    types:
      - completed
jobs:
  notify:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Notify Webhook
        run: |
          echo "Kick Deploy"
        