name: Packages
on:
  push:
  pull_request:
jobs:
  generator:
    name: generator
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file_name:
          - first
          - second
          - third
    steps:
      - name: Create a sample file
        run: |
          echo "${{ matrix.file_name }}" > "${{ matrix.file_name }}.txt"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.file_name }}
          path: "${{ matrix.file_name }}.txt"
  release:
    if: |
      github.ref_type == 'tag'
    needs: generator
    uses: ./.github/workflows/release.yml
    with:
      workflow_id: ${{ github.run_id }}
      tag: ${{ github.ref_name }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
