name: Packages
on:
  push:
  pull_request:
jobs:
  generator:
    name: generator
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file_name:
          - first
          - second
          - third
    steps:
      - name: Create an asset
        run: |
          echo "${{ matrix.file_name }}" > "${{ matrix.file_name }}.txt"
          zip "${{ matrix.file_name }}.zip" "${{ matrix.file_name }}.txt"
          mv "${{ matrix.file_name }}.txt" "${{ matrix.file_name }}.md"
          tar czf ${{ matrix.file_name }}.tar.gz "${{ matrix.file_name }}.md"
      - name: Upload artifact zip
        uses: actions/upload-artifact@v4
        with:
          name: "${{ matrix.file_name }}.zip"
          path: "${{ matrix.file_name }}.zip"
      - name: Upload artifact tar.gz
        uses: actions/upload-artifact@v4
        with:
          name: "${{ matrix.file_name }}.tar.gz"
          path: "${{ matrix.file_name }}.tar.gz"
      - name: Collect artifact names
        run: |
          echo "${{ matrix.file_name }}.zip" >> "${{ matrix.file_name }}-artifacts.txt"
          echo "${{ matrix.file_name }}.tar.gz" >> "${{ matrix.file_name }}-artifacts.txt"
      - name: Upload artifact tar.gz
        uses: actions/upload-artifact@v4
        with:
          name: "${{ matrix.file_name }}-artifacts.txt"
          path: "${{ matrix.file_name }}-artifacts.txt"
  release:
    if: |
      github.ref_type == 'tag'
    needs: generator
    uses: ./.github/workflows/release.yml
    with:
      workflow_id: ${{ github.run_id }}
      tag: ${{ github.ref_name }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
