name: release
on:
  workflow_call:
    inputs:
      workflow_id:
        required: true
        type: string
      tag:
        required: true
        type: string
    secrets:
      token:
        required: true
jobs:
  uploader:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create GitHub Release
        run: |
          gh release create "${{ inputs.tag }}" \
            --title "release-${{ inputs.tag }}" | :
        env:
          GH_TOKEN: ${{ secrets.token }}
      - uses: actions/download-artifact@v4
        with:
          path: ./artifacts/downloads
      - name: List artifacts
        run: ls -la ./artifacts/downloads/
      - name: Unzip Artifacts
        run: |
          mkdir -p ./artifacts/releases
          for artifact in ./artifacts/downloads/*; do
            echo "Unzipping $artifact"
            unzip "$artifact" -d "./artifacts/releases/"
          done
      - name: Upload Individual Files to Release
        run: |
          gh release upload "${GITHUB_REF_NAME}" artifacts/releases/*
        env:
          GH_TOKEN: ${{ secrets.token }}
