name: release
on:
  workflow_call:
    inputs:
      workflow_id:
        required: true
        type: string
      tag:
        required: true
        type: string
    secrets:
      token:
        required: true
jobs:
  uploader:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create GitHub Release
        run: |
          gh release create "${{ inputs.tag }}" \
            --title "release-${{ inputs.tag }}" | :
        env:
          GH_TOKEN: ${{ secrets.token }}
      - uses: actions/download-artifact@v4
        with:
          path: ./artifacts/downloads
          merge-multiple: true
      - name: Upload Individual Files to Release
        run: |
          gh release upload "${GITHUB_REF_NAME}" artifacts/downloads/*
        env:
          GH_TOKEN: ${{ secrets.token }}
