name: Reusable workflow example
on:
  workflow_call:
    inputs:
      workflow_id:
        required: true
        type: string
    secrets:
      token:
        required: true

name: Reusable workflow example
on:
  workflow_call:
    inputs:
      workflow_id:
        required: true
        type: string
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Print workflow_id
        run: |
          echo "workflow_id: ${{ inputs.workflow_id }}"
      with:
        repo-token: ${{ secrets.token }}
        configuration-path: ${{ inputs.config-path }}
