name: Reusable workflow example
on:
  workflow_call:
    inputs:
      workflow_id:
        required: true
        type: string
jobs:
  test:
    name: called-workflow
    runs-on: ubuntu-latest
    steps:
      - name: Print workflow_id
        run: |
          echo "workflow_id: ${{ inputs.workflow_id }}"
